CREATE TABLE IF NOT EXISTS KUPOVINA
(
  idKupovina BIGINT GENERATED ALWAYS AS IDENTITY,
  idKorisnik BIGINT NOT NULL,
  proizvodId BIGINT NOT NULL,
  datKupnje TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (idKupovina),
  FOREIGN KEY (idKorisnik) REFERENCES POLAZNIK(idKorisnik) ON DELETE CASCADE,
  FOREIGN KEY (proizvodId) REFERENCES PROIZVOD(proizvodId) ON DELETE CASCADE,
  UNIQUE (idKorisnik, proizvodId)
);
